services:
  app:
    build: .
    tty: true
    stdin_open: true
    restart: always
    environment:
      APP_NAME: 'BLOG14'
      APP_URL: 'https://blog.amiverse.net/'
      AUTHOR_NAME: 'KISANA:ME'
      AUTHOR_ID: 'kisana_me'
      RAILS_ENV: production
      RAILS_SECURE_COOKIES: 'true'
      S3_LOCAL_ENDPOINT: 'http://minio:9000/'
      S3_PUBLIC_ENDPOINT: 'https://blog.amiverse.net/'
      S3_USER: 'minioroot'
      S3_PASSWORD: 'minioroot'
      S3_REGION: 'blog14'
      S3_BUCKET: 'production'
      INVITATION_CODE: 'zettainibarenaiko-dowosiyousitekudasai'
      GA4_ID: '2PND2STXF8'
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - minio
    command: >
      bash -c "rm -f /app/tmp/pids/server.pid &&
      rm -rf /app/public/assets &&
      gem cleanup &&
      bundle install -j4 &&
      rails db:migrate &&
      RAILS_ENV=production rails assets:precompile &&
      rails s -b 0.0.0.0"

  db:
    image: mariadb:latest
    tty: true
    stdin_open: true
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
      MARIADB_ROOT_PASSWORD: 'mdbroot'
    volumes:
      - db-vol:/var/lib/mysql
    ports:
      - '3306:3306'

  minio:
    image: minio/minio:latest
    tty: true
    stdin_open: true
    restart: always
    environment:
      MINIO_ROOT_USER: 'minioroot'
      MINIO_ROOT_PASSWORD: 'minioroot'
    volumes:
      - minio-vol:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"

  phpmyadmin:
    image: phpmyadmin:latest
    tty: true
    stdin_open: true
    restart: always
    environment:
      PMA_HOSTS: 'db'
    depends_on:
      - db
    ports:
      - '8080:80'

volumes:
  db-vol:
  minio-vol: