inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
